apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rr01nnbp2-go 
  janus-idp.io/tekton: rr01nnbp2-go
  backstage.io/kubernetes-id: rr01nnbp2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rr01nnbp2-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  